### ISSUE TITLE
Add LICENSE file and all the stuff :)

### ISSUE THREAD

**Issue by GermanBluefox** [ruhigundrelaxed/ioBroker.hyperion#7]
https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-repository

**Comment by ruhigundrelaxed** [comment]
1. ) Adapter needs to be available as package on npm. See How to publish on npm

DONE

    2.) iobroker organisation must be added as owner to npm package. Why and how to do that.

DONE

    3.) Adapter needs to have a README.md with description, detail information and changelog. English is mandatory. Other languages are welcome. See Example of README.md

OK

    4.)Adapter must have a predefined license.

OK (MIT)

    5.)Adapter needs to have at least Adapter basic testing (installing, running) using Travis-CI and Appveyor. More information in Forum from apollon77 (Just take from other adapters the samples)

??? (Open)

6.)    Define one of the types in io-package.json

OK

7.) Include "author" in io-package.json and "authors" in io-package.json

OK

8.)    Add your adapter into the list (first latest and after that into stable, when tested). Examples of entries you can find here. Note: don't forget to add attribute published to both repositories.

PLEASE HELP!

9.)  Your github repository must have name "ioBroker.". B is capital in "ioBroker", but in the package.json the name must be low case, because npm does not allow upper case letters.


OK


10.) title in io-package.json (common) is simple short name of adapter in english. titleLang is object that consist short names in many languages. Lang ist not german Länge, but english LANGuages.


OK :-)


11.)     Do not use in the title the words "ioBroker" or "Adapter". It is clear anyway, that it is adapter for ioBroker.


OK

Thx

**Comment by ruhigundrelaxed** [comment]
Done
